### PR TITLE
Implement workaround for a known CJK layout bug

### LINKED ISSUE #11: Workaround for a known CJK layout bug
source: https://github.com/noraesae/kawa/issues/2#issuecomment-329489897

There's a known TIS bug about CJK, also written in README.

> There is a known bug in the TIS library of macOS that switching keyboard layouts doesn't work well when done programmingly, especially between complex input sources like CJK. Kawa once tried to resolve this problem using hacky workaround, which caused more bugs, did more bad than good. The option is removed in v0.1.3, and I decide to wait for the fix from macOS.

However, @zcbenz suggested a workaround, and I'd like to check if it works.

- If target is English
    - Select English
- If target is a language other than English
    - Switch to target language
    - Switch to English
    - Select previous language

ref:

- https://github.com/CodeFalling/fcitx-remote-for-osx/blob/7f7e2895d413df44f45ef5c9aa3d127e428a7cbc/fcitx-remote/main.m#L69
- https://github.com/tekezo/Karabiner/issues/308#issuecomment-190693550

### PR DESCRIPTION
**Pull request by hatashiro**
Fix #11 

It works like below:

- Select an input source
- If the source is CJK
    - Switch to English `com.apple.keylayout.US`
    - Wait for 0.05
    - Select previous source (in this case, the original source)

### CODE REVIEW

**Comment by laughedelic** [comment]
About the limitations you mention in the readme:
- is it possible make particular English layout a setting or somehow determine which one has English language among those that user has installed? I'm using a custom English layout that I made with [Ukulele](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele) to combine normal English with some shortcuts for typing Spanish and pinyin. It wasn't very easy to get rid of the system standard English layout (it's kind of obligatory if your system language is English) and I don't want to have two English layouts again.
- What about that shortcut? Isn't it possible to call the command programmatically without relying on a particular shortcut?
- Is the whole back-and-forth switching with the `0.05`s delay noticeably slower than normal switching? Could the artificial delay be lowered?

**Comment by hatashiro** [comment]
@laughedelic 

- For checking English, now I think it could be any non-complex(or non-CJK) input source. I'd rather not adding a setting for it.
- For shortcut, I'm not sure if it can be done programmatically. All other implementations did the same way. I will check, but it is likely to be impossible.
- The reason why back-and-forth switching is slow is not because of the 0.05s delay, but because `Select the previous input source` itself is somewhat slow. I will check if shorter delay do the same.

If you have a specific suggestion in implementation level, please let me know.

**Comment by laughedelic** [comment]
Thanks for reply. I'll try to make some suggestions on the code.

File: kawa/InputSourceManager.swift [hunk 1]
```diff
@@ -88,19 +100,17 @@ class InputSourceManager {
             }
     }
     
-    static func tweak() {
-        selectPrevious()
-        Timer.scheduledTimer(timeInterval: 0.3, target: self, selector: #selector(selectPrevious), userInfo: nil, repeats: false)
+    static func englishSource() -> InputSource? {
+        return inputSources.first(where: { $0.id == "com.apple.keylayout.US" })
```
Comment (laughedelic) [inline kawa/InputSourceManager.swift]: Could it be made a `nonCJKSource` instead? Same way you check above for CJK, you could check here something like
```swift
inputSources.first($0.langs.notContains(where: { $0 == "ko" || $0 == "ja" || $0.hasPrefix("zh") }))
```

(not the real code, because I see that you need to get `langs somehow`), but I think you get the idea)

If it's slow to do such search every time, it could be somehow cached once found..

**Comment by hatashiro** [comment]
@laughedelic 

I've applied the non-CJK checking code with instance property caching. Also I've confirmed that it works without the thread sleep :)

I'll look into the shortcut thing.

**Comment by laughedelic** [comment]
Wow! That's great! 👍

File: kawa/InputSourceManager.swift [hunk 2]
```diff
@@ -36,6 +37,9 @@ class InputSource: Equatable {
         id = InputSource.getProperty(tisInputSource, kTISPropertyInputSourceID)!
         name = InputSource.getProperty(tisInputSource, kTISPropertyLocalizedName)!
 
+        let langs: Array<String> = InputSource.getProperty(tisInputSource, kTISPropertyInputSourceLanguages)!
+        isCJK = langs.contains(where: { $0 == "ko" || $0 == "ja" || $0.hasPrefix("zh") })
```
Comment (laughedelic) [inline kawa/InputSourceManager.swift]: I don't know much about that bug, but I saw somewhere that it's "CJKV-related", so _probably_ Vietnamese also deserves to be here.. Or if it's about all complicated input sources, _probably_ Arabic and Hebrew should also be here (just guessing).

**Comment by hatashiro** [comment]
@laughedelic 

I added Vietnamese to the checklist. I will add others when there's any issue reported.

Also, a good news, there *is* actually a way to retrieve the shortcut of `Select the previous input source` and I wrote a commit to use it.

ref:

- https://github.com/tekezo/Karabiner/search?utf8=%E2%9C%93&q=ENV_Select_the_previous_input_source_shortcut
- https://github.com/tekezo/Karabiner/blob/master/src/lib/xml_compiler/src/xml_compiler.cpp
- https://github.com/tekezo/Karabiner/blob/master/src/util/read-symbolichotkeys/read-symbolichotkeys/main.m

Thank you very much for pushing me to look for them 💯

**Comment by laughedelic** [comment]
Awesome! I'm very glad you managed to implement this workaround and overcome all initial limitations! 👍 👍 👍 

I'm looking forward to install a new version of Kawa 😊

**Comment by zcbenz** [comment]
👍 Can't wait for a new release, it solves my years of pains.

**Comment by hatashiro** [comment]
Merged 🎉 🎉 🎉 

Thanks everybody: @laughedelic @zcbenz @alldne

**Comment by laughedelic** [comment]
Works like a charm! Thanks a lot for this release! 👏 
And a **big thank** to @zcbenz for finding the workaround! :1st_place_medal:

**Comment by Yang-Xijie** [comment]
Applescript and UI operation might be a workaround.

Check <https://github.com/Yang-Xijie/InputSourceSwitcher>.

**Comment by GJRobert** [comment]
> Applescript and UI operation might be a workaround.
> 
> Check https://github.com/Yang-Xijie/InputSourceSwitcher.

Great to see new workaround after 4 years of Kawa! Your Source Switcher works on my machine.
